version = 1

[install]
ios-tooling.flake = "github:segment-integrations/templates#ios-tooling"

[vars]

[hook]
 on-activate = ''

[profile]

[services]

[include]
 environments = [
     { dir = "./min" },
     { dir = "./max" }
 ]

[build]

[options]
