name: iOS Simulator Service

on:
  push:
  pull_request:

jobs:
  ios-simulator:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
      - name: Start iOS simulator service
        working-directory: devbox/examples/ios
        run: SIM_HEADLESS=1 devbox run --pure start-sim
      - name: Wait for simulator to settle
        run: sleep 20
      - name: Stop iOS simulator service
        working-directory: devbox/examples/ios
        run: devbox run --pure stop-sim
